name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and Build
      run: |
        npm ci
        npm run build
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # The folder the action should deploy.
        git-config-name: GitHub Actions
        git-config-email: sandychad@outlook.com
        ssh-key: MIIJKAIBAAKCAgEAmmyVjtuUHTmTovboi8RNdwx98M5l1eDBqAAchvZjP9iuTgcN08J+lE4yDV4t4rtA2pmjM27a48gelx1KJ7ImciAEtI5dvqT4wx40G0H2LuFmTiJ1JviHCK+k4GtPEejfNc5iZ8BCi2VnxaBN8HH0uJUSl1p0T46ZZDy5j7INXnnZgzAtj9MYRH/aouzCKlyvD5F8ENguNxSu83A1mM/qdmxA60D9yahDQgy8yOKZs9gS6dZsmiqz6vimRGnTM3vbs0jw2b+oBaLQATFwhhYYgiInesVWCB+JFnPlWUXE7Bs1ytXTc3HuQ+yyOxXDXMlm85/xmFlEFJUXrNjjSGkJe6ax9t9HG2aJH5OMl2kCM9kpD/Gc1pCLfGPQUui6EVQ08b0ncksLcCIJPH+pJdeEpnchybhN/Aq/XqsW0BwKWt7bsPph9LLS3SfQWrpVzS5ROi6L9GVx6/oosa4dpB5VljH8ndpLxxHjBaTO/K43fFOyfuvfKY+eElNMuPzpZXw0rrodtEh9IXNAdWW+qnKMdLW9hRXHu6HrKsVuqiHnCdVFqNAPw095MCEFTvRC2Nv+VQPAZO9kFvd9A8C5FE5y8CZxW+1dmK9iUWiLH6FHZYxUh3bTTIo5mLOUHvkeFe8f4A8T4xA+QTk5BmnlQeSUiEQR1treblZr0rx0LmOjTasCAwEAAQKCAgBmEduQ/4YZAxOYpcbzix8Az1r3LhWVluep2dkBRB4590jO/k6fZ3EvKbhfqZ5+vPKTCvYaau13nbDKhWucbV6IFK3HgkpoVraukWozkhfcyNNMVe5FggQPM7mxNHyhA+F1uSLGHQhfBvneYKTjhw8QakhNjlZOt5yf6ptkZXX8umGRGukipY7mx/OFuSRlx7lWev0cTSfO9HbnJYXnqZX6DHekh+K3xeYe5DhsN4sMmod11GsYQ52EdDHCCoi1AOsox8+avdmbUBBYmYsctcIhUd3ygjjpSZ7dHmG77ifJP/sARPFs3yNz9iGgeDQXQnAwG8oevvIHAL0TXJBuLi87awlvH4nQktvk4Nq6jgFBpJgiAIVuXBYvYozqB0A9CXy2EPtruhEMzgG6Bz4dClDy7TlTM4TaRCkcJIoIaw4Q3mn8g11Xl4o5HoBI8xcd1wmWp0wqZEda3hwCN7wzXMmx8MPPhl8E0IE+YcohHgnqxKnh+WMMzaGaAscU3zEA2i7kV4FBomfm1AnT8x/QppaDNWAlOlqKsUE/9J0Ncm5jMoCbERRYScufUmanOz7+fF6Te9F3NkP09xHOPpxP0lmgl4+6tr3c+3ErJcGVC3EkVO58RNlt59ITS3BnL85cvrRcJe1QqErG+BVxb7PuCLOxXcCe2GHEf/fVWcdzCYahwQKCAQEAyQTcem8pJBBFoktYkrSEtM11cjjEJXq6jiGUyAgCTowmFwX2R2Fxi87mCxJWFjsL1vglkSaxHjN+yTJfzI3k8ZeAtLYJoLhkyLaAGoIBnb0dCeWx8whlN51kjF0c1Q/qon0Cle6zH7iyWeKRPv070is4OFR22AfsbzLjqFQwsGa6w/5F6czXh8Opi2zKzNpkQj8FJzt0MHkSlTdmukskK37Ui0CcfZJVRyXFOTt1rgn2StuJ25QYP4hfvBB1VZZnnxqG0Nug2w9lzaQ5hSX7HhosqV7SfuhhyQ0OqQNRGZqpB2pPP3yjSpaM5juOh4XFpDIhJzveunKf5rJjO6+OkQKCAQEAxKkzooAsbnxBxdsRnHKiWqiCiRYX0pb+v5cNh9TdmCQHaRX0xyGmj22xiwib0Ttv03I/DiGSweGluGqb2OvWPdvjITJ9fH4O15TT+T3w8vrW6voY+zOZSMwkOdBxY/pmGyXq/SvOlGmE889ux0b3DkWgZHyJgpXOrxt6crk1WDjz0TZv5Ydr1J/jf4X2un26ee2EcabnAi0296EwnVqAbGAMfAifQq9Cx8cP1gL37rm12o/zIb2n064F2KaxHHohPgVAj20Jigl7XGteKsAPLt7ICv1Lqy1P2LGTM5kzFKdqbnjgmQG7CeZkiiTNkFIblPPh2oqY9cnRZZKg8U/uewKCAQBllaZR3SEeT3bRKGBvavhxYi8K9PLyuc3TC9djKuD3js2k7udhdTXrYDhSugZ1H4vBLA/YBYSWbZGR3XoaJk7fZB+vsxq0dNrBr7CXNMHaU/p7yO8fkUuNSmXIpTlv1qZNTP1khYdR7YV79QpPmauEb0Du/og8beym2UHBDCK60n9pknMETvdQbamdgvINigQGklBpXhs+b8DbVW79kAGMVYDVimZK8wtTdBvx60FyHSiw9bb6FyIV4TX4FR0mjmZ5Oe+NVqA4c9SPkoFa7zGzKakOQpP/fDIGZynUcY+nb8ghrjC0NalThTdZFhnWFN0nOAoXCKNq94glDlsl
